### ISSUE TITLE
Frontend: Close Choose Filters Modal

### ISSUE THREAD

**Issue by elizabethfoster02** [elizabethfoster02/CasaMyrnaProject#11]
**Purpose**
Currently, if you open the Choose Filters Modal, it doesn’t not close unless you refresh the page

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
