### ISSUE TITLE
Getting user id associated with shift

### ISSUE THREAD

**Issue by elizabethfoster02** [elizabethfoster02/CasaMyrnaProject#12]
**Assignees**
Bill + Sean
(more of a mark of what you guys have already been doing)

**Purpose**
On the shift object, get the user id associated with shift (previously hardcoded)

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
