### ISSUE TITLE
Frontend: Replace "Canceled" with "Available"

### ISSUE THREAD

**Issue by elizabethfoster02** [elizabethfoster02/CasaMyrnaProject#9]
**Purpose**
We got this feedback from the client -- but they'd prefer if we changed the name of "canceled" shifts to "available" shifts. Please change every frontend instance of "canceled" to be "available"

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
